### ISSUE TITLE
Organization dropdown does not work on user create form.

### ISSUE THREAD

**Issue by lagoan** [portagenetwork/roadmap#57] opened 2021-08-10 18:37 UTC
**Expected behaviour:**

The organization dropdown menu should autopopulate as the user starts typing the name of her organization.

**Actual behaviour:**
The Organization list/dropdown menu doesn’t seem to work/auto populate when creating or editing an account, but works for selecting templates creating plans = is this because the production instance database isn’t linked?

**Steps to reproduce:**
Create an account and the drop down is not populated from database.

**Comment by lagoan** [comment] 2022-03-28 17:16
@pengyin-shan is this still an issue ?

**Comment by pengyin-shan** [comment] 2022-03-31 21:16
The issue is still there. Pending to be fixed

**Comment by pengyin-shan** [comment] 2022-03-31 21:24
![Screen Shot 2022-03-31 at 17 23 35](https://user-images.githubusercontent.com/92752107/161151709-b6e1baa4-c307-42dc-8f15-fcbb2f04b4fd.png)
Noticed same error message as the JSON download issue

**Comment by pengyin-shan** [comment] 2022-11-15 22:31
Close this issue since the organizational dropdown is working when creating or updating the user's organization. JSON download also works.

**Closed by pengyin-shan** 2022-11-15 22:31 UTC
Labels: bug, dmp upgrade v3
